services:
  server:
    build: ./docker/nginx
    container_name: t_server
    ports:
      - 8085:80
    volumes: 
      - type: bind
        source: ./www/yii/web
        target: /var/www/html/web
    depends_on:
      - php
  database:

    # Пока не трогать, но нужно создать для неё Dockerfile
    image: mysql:5.7.41
    container_name: t_database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: testdb # Особенный флаг для Docker
    volumes:
      - tDatabaseData:/var/lib/mysql # Привязка Volume для хранения БД
      - ./mysql/scripts/:/docker-entrypoint-initdb.d/
      - ./data/images/:/data/images/
  phpmyadmin:

    # Нужно будет создать для неё Dockerfile
    image: phpmyadmin/phpmyadmin:latest
    container_name: t_phpmyadmin
    environment:
      PMA_HOST: t_database
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - 8086:80
    depends_on:
      - database
  php:
    build: ./docker/php
    container_name: t_php
    volumes:
      - type: bind
        source: ./www/yii/controllers
        target: /var/www/yii/controllers
      - type: bind
        source: ./www/yii/models
        target: /var/www/yii/models
      - type: bind
        source: ./www/yii/views
        target: /var/www/yii/views
      - type: bind
        source: ./www/yii/web
        target: /var/www/yii/web
volumes:
  tDatabaseData: